enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app

[Messenger]
enabled = true
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"
version = "auto"
